dist: trusty
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11

jobs:
  include:
    - jdk: openjdk7
      env: EXTRA_MVN="-Dcheckstyle.version=2.15 -Dcheckstyle.skip"

install: mvn clean install -Dgpg.skip $EXTRA_MVN
