version: 2.1

orbs:
  win: circleci/windows@2.4.1

commands:
  create_custom_cache_lock:
    description: "Create custom cache lock for java version."
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Grab java version and dump to file
          command: java -version > << parameters.filename >>

default_steps_7-11: &default_steps_7-11
  steps:
    - checkout
    - run: mvn clean install
    - run: cd dogstatsd-http-serializer && mvn clean install

default_steps_11-21: &default_steps_11-21
  steps:
    - checkout
    - run: mvn clean install
    - run: cd dogstatsd-http-serializer && mvn clean install
    - run: cd dogstatsd-http-forwarder && mvn clean install

default_steps_21-24: &default_steps_21-24
  # Java 7 source code is not compatible with OpenJDK 21 and later.
  steps:
    - checkout
    - run: cd dogstatsd-http-forwarder && mvn clean install

jobs:
  openjdk7:
    docker:
      - image: jfullaondo/openjdk:7
    <<: *default_steps_7-11
  openjdk8:
    docker: &jdk8
      - image: cimg/openjdk:8.0
    <<: *default_steps_7-11
  openjdk11:
    docker:
      - image: cimg/openjdk:11.0
    <<: *default_steps_11-21
  openjdk13:
    docker:
      - image: cimg/openjdk:13.0
    <<: *default_steps_11-21
  openjdk17:
    docker:
      - image: cimg/openjdk:17.0
    <<: *default_steps_11-21
  openjdk21:
    docker:
      - image: cimg/openjdk:21.0
    <<: *default_steps_21-24
  openjdk24:
    docker:
      - image: cimg/openjdk:24.0
    <<: *default_steps_21-24

  windows-openjdk12:
    executor:
      # https://github.com/CircleCI-Public/windows-orb/blob/v2.4.1/src/executors/default.yml
      name: win/default
      # https://circleci.com/developer/machine/image/windows-server-2019
      version: 2023.04.1
    steps:
      - checkout
      - run: java -version
      - run: |
          choco install maven
      - run: |
          mvn clean install

  openjdk8-jnr-exclude:
    docker: *jdk8
    steps:
      - checkout
      - run: "mvn -Pjnr-exclude clean test"
  openjdk8-jnr-latest:
     docker: *jdk8
     steps:
       - checkout
       - run: "mvn clean test -DskipTests" # build main and test with default deps
       - run: "mvn -Pjnr-latest test"      # run with modified deps

workflows:
  version: 2
  agent-tests:
    jobs:
      - openjdk7
      - openjdk8
      - openjdk11
      - openjdk13
      - openjdk17
      - openjdk21
      - openjdk24
      - windows-openjdk12
      - openjdk8-jnr-exclude
      - openjdk8-jnr-latest
