version: 2.1

orbs:
  win: circleci/windows@2.4.1

commands:
  create_custom_cache_lock:
    description: "Create custom cache lock for java version."
    parameters:
      filename:
        type: string
    steps:
      - run:
          name: Grab java version and dump to file
          command: java -version > << parameters.filename >>

default_steps: &default_steps
  steps:
    - checkout

    - run: |
        mvn clean install $MVN_EXTRA_OPTS

jobs:
  openjdk7:
    docker:
      - image: jfullaondo/openjdk:7
    environment:
      MVN_EXTRA_OPTS: -Dcheckstyle.version=2.15 -Dcheckstyle.skip
    <<: *default_steps
  openjdk8:
    docker: &jdk8
      - image: cimg/openjdk:8.0
    <<: *default_steps
  openjdk11:
    docker:
      - image: cimg/openjdk:11.0
    <<: *default_steps
  openjdk13:
    docker:
      - image: cimg/openjdk:13.0
    <<: *default_steps
  openjdk17:
    docker:
      - image: cimg/openjdk:17.0
    <<: *default_steps

## Fails with "Source option 7 is no longer supported. Use 8 or later."
#  openjdk21:
#    docker:
#      - image: cimg/openjdk:21.0
#    <<: *default_steps

  windows-openjdk12:
    executor:
      # https://github.com/CircleCI-Public/windows-orb/blob/v2.4.1/src/executors/default.yml
      name: win/default
      # https://circleci.com/developer/machine/image/windows-server-2019
      version: 2023.04.1
    steps:
      - checkout
      - run: |
          choco install maven
      - run: |
          mvn clean install

  openjdk8-jnr-exclude:
    docker: *jdk8
    steps:
      - checkout
      - run: "mvn -Pjnr-exclude clean test"
  openjdk8-jnr-latest:
     docker: *jdk8
     steps:
       - checkout
       - run: "mvn clean test -DskipTests" # build main and test with default deps
       - run: "mvn -Pjnr-latest test"      # run with modified deps

workflows:
  version: 2
  agent-tests:
    jobs:
      - openjdk7
      - openjdk8
      - openjdk11
      - openjdk13
      - openjdk17
#      - openjdk21
      - windows-openjdk12
      - openjdk8-jnr-exclude
      - openjdk8-jnr-latest
