version: 2.1

default_steps: &default_steps
  steps:
    - checkout
    - run: |
        mvn clean install -Dgpg.skip $EXTRA_MVN
jobs:
  openjdk7:
    docker:
        - image: openjdk:7-jdk
    <<: *default_steps
  openjdk8:
    docker:
        - image: circleci/openjdk:8u242
    <<: *default_steps
  openjdk9:
    docker:
        - image: circleci/openjdk:9.0.4-12
    <<: *default_steps
  openjdk11:
    docker:
        - image: circleci/openjdk:11.0.2
    <<: *default_steps
  openjdk13:
    docker:
        - image: circleci/openjdk:13.0.2-buster
    <<: *default_steps

workflows:
  version: 2
  agent-tests:
    jobs:
      - openjdk7
      - openjdk8
      - openjdk9
      - openjdk11
      - openjdk13
